### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by evilslashxd** [LeoColomb/yourls-ua-stats#1]
This plugin no longer works with the latest version of YOURLS?

**Comment by LeoColomb** [comment]
Thanks for opening this issue @evilslashxd.
That said I don't know, I'm not using it actively.
Have you tried it?

**Comment by evilslashxd** [comment]
Si, lo he estoy probando y a la hora de activarlo da error , si sabes cómo arreglarlo por favor, necesito justo esto saber desde que dispositivo y SO dan click por favor

**Comment by LeoColomb** [comment]
@evilslashxd Sorry, but you need to write in English. And please describe the issue you're having, if any.

**Comment by evilslashxd** [comment]
Well, I have the latest version of YOURLS, 1.8.2, the shortener works fine, but when I install this plugin when I activate it, it does nothing, it gives an error, I was looking for another plugin that fulfills the same function and does not It does, I require this because it counts each click by browser and operating system, from mobile or desktop, please, if you can guide me, I would appreciate it.

**Comment by LeoColomb** [comment]
> it gives an error

What error? What is inside the PHP log file? Which PHP version?

**Comment by evilslashxd** [comment]
When activating the page remains blank. It does not give an error or anything, the plugin is not activated and it remains blank, I was looking for another similar plugin but I did not find any I have the latest version of YOURLS and PHP

**Comment by LeoColomb** [comment]
@evilslashxd I can't help you if you say the opposite of your previous comment each time.

* Does it give an error or not?
* How the interface looks like? (screenshot?)
* What is logged in the log files?
* Which PHP version?

**Comment by evilslashxd** [comment]
Visually it does not give any error, I do not know much about programming and I do not know where the error may have I did the steps and simply by activating the complement it remains blank, it does nothing, I take a step back and the complement is deactivated, I have
PHP Version 7.2.31
Yourls Version 1.8.2

![paso 1](https://user-images.githubusercontent.com/91446401/138972097-8b9cdf39-ae54-4a33-82ef-4ad75980a567.png)

I give activate complement

![paso 2](https://user-images.githubusercontent.com/91446401/138972210-734b70f1-39ad-445c-93aa-d6d1c4eb8361.png)

**Comment by LeoColomb** [comment]
> PHP Version 7.2.31
> Yourls Version 1.8.2

Nothing from this is supported.
This plugin can't work with this tooling, and was targeting YOURLS 1.2 with PHP < 7.

I'm actually archiving this plugin as outdated and end of support.
